# Generated by Django 4.2.4 on 2023-08-19 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='',max_length=100)),
                ('contact', models.CharField(default='',max_length=10, serialize=False, unique=True)),
                ('pwd', models.CharField(default='',max_length=20)),
            ],
            options={
                'db_table': 'staffs',
            },
        ),
    ]
