# Generated by Django 4.2.4 on 2023-08-25 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='',max_length=100)),
                ('contact', models.CharField(default='',max_length=10, serialize=False, unique=True)),
                ('pwd', models.CharField(default='',max_length=20)),
                ('status', models.CharField(default='unavailable',max_length=11)),
                ('count', models.IntegerField(default=0,max_length=3)),
                ('checkedIn', models.CharField(default='F',max_length=1)),
            ],
            options={
                'db_table': 'doctors',
            },
        ),
    ]
